// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVv6MUeJoG9V7vuIiPne3TIY2YW4pzGOY',
    appId: '1:517887023342:web:71255ebd5a6d55be6d7bff',
    messagingSenderId: '517887023342',
    projectId: 'fishcare-6a320',
    authDomain: 'fishcare-6a320.firebaseapp.com',
    databaseURL: 'https://fishcare-6a320-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fishcare-6a320.appspot.com',
    measurementId: 'G-9C9G9KRT96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-aVpUXs-LKuSKGfNob-xY1zGcldQFBsc',
    appId: '1:517887023342:android:921940e7bf1395086d7bff',
    messagingSenderId: '517887023342',
    projectId: 'fishcare-6a320',
    databaseURL: 'https://fishcare-6a320-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fishcare-6a320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyt2invxgEWv3SGDGmcKBiTrZgfsi80j8',
    appId: '1:517887023342:ios:355ac0b02fde2d3d6d7bff',
    messagingSenderId: '517887023342',
    projectId: 'fishcare-6a320',
    databaseURL: 'https://fishcare-6a320-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fishcare-6a320.appspot.com',
    iosClientId: '517887023342-3tom7dvlpppt16pmles4fqf7hbramcc5.apps.googleusercontent.com',
    iosBundleId: 'com.test.fishCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyt2invxgEWv3SGDGmcKBiTrZgfsi80j8',
    appId: '1:517887023342:ios:355ac0b02fde2d3d6d7bff',
    messagingSenderId: '517887023342',
    projectId: 'fishcare-6a320',
    databaseURL: 'https://fishcare-6a320-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fishcare-6a320.appspot.com',
    iosClientId: '517887023342-3tom7dvlpppt16pmles4fqf7hbramcc5.apps.googleusercontent.com',
    iosBundleId: 'com.test.fishCare',
  );
}
